export default function Head() {
  return (
    <>
      <title>Bethel Pharr - Serve God with love</title>
      <meta name="title" content="Bethel Pharr - Serve God with love" />
      <meta
        name="description"
        content="Discover the transformative power of faith at our vibrant Pentecostal church affiliated with the esteemed Assemblies of God in Pharr, Texas. Immerse yourself in divine encounters as you join us every Sunday and Wednesday, where God's presence embraces our worship gatherings."
      />

      <meta property="og:type" content="website" />
      <meta
        property="og:url"
        content="https://bethel-template-418n-git-pre-release-zeviks.vercel.app/"
      />
      <meta property="og:title" content="Bethel Pharr - Serve God with love" />
      <meta
        property="og:description"
        content="Discover the transformative power of faith at our vibrant Pentecostal church affiliated with the esteemed Assemblies of God in Pharr, Texas. Immerse yourself in divine encounters as you join us every Sunday and Wednesday, where God's presence embraces our worship gatherings."
      />
      <meta
        property="og:image"
        content="https://metatags.io/images/meta-tags.png"
      />

      <meta property="twitter:card" content="summary_large_image" />
      <meta
        property="twitter:url"
        content="https://bethel-template-418n-git-pre-release-zeviks.vercel.app/"
      />
      <meta
        property="twitter:title"
        content="Bethel Pharr - Serve God with love"
      />
      <meta
        property="twitter:description"
        content="Discover the transformative power of faith at our vibrant Pentecostal church affiliated with the esteemed Assemblies of God in Pharr, Texas. Immerse yourself in divine encounters as you join us every Sunday and Wednesday, where God's presence embraces our worship gatherings."
      />
      <meta
        property="twitter:image"
        content="https://metatags.io/images/meta-tags.png"
      />

      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <meta name="apple-mobile-web-app-status-bar-style" content="black" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/images/favicon.ico" />
    </>
  );
}
